language: ruby
cache: bundler
sudo: false

os:
- linux
- osx

rvm:
- 2.5
- 2.4
- 2.3
- 2.2
- 2.1
- 2.0
- 1.9.3
- ruby-head
- jruby-9.2
- jruby-head
- rbx-3

env:
  global:
    - JRUBY_OPTS='--debug -J-Xmx1000M'

before_install:
  - echo 'gem: --no-document --verbose --env-shebang' > ~/.gemrc
  - rvm @global do gem uninstall bundler -Iax || true
#  - gem uninstall bundler -Iax || true
#  - gem install bundler -v '~> 1.11.2'
  - gem update --system
  - gem update --remote bundler
  - bundle config --global jobs 4
  - bundle config --global retry 4

matrix:
  fast_finish: true
